version: '3.8'

services:
  app:
    build: .
    command: bun dev
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
