services:
  app:
    build: .
    command: bun dev
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
    ports:
      - "9001:9001"
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    depends_on:
      - redis
      - db

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    expose:
      - 9002
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: